spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/workflow?characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
#camunda:
#  bpm:
#    database:
#      # 每次启动删除表再建表
#      schema-update: drop-create
